### ISSUE TITLE
Font rendering broken on Windows Chrome 32-bit

### ISSUE THREAD

**Issue by TETYYS** [a1k0n/jsxm#16]
Try to play this awesome xm https://up1.ca/#CDY7u_uzDonNj_RIZ0nP9A , jsxm doesn't show any notes
Another example is this: https://up1.ca/#VM-W3hZqc38yzHBhtcflSA and this https://up1.ca/#QnK7MulFvLK-WwCSGqRd5A

**Comment by a1k0n** [comment]
All of them seem to work fine for me if I drag and drop onto the player.

What OS/browser? How are you trying to play them?

**Comment by TETYYS** [comment]
drag and drop, win 7 chrome 46 latest

**Comment by a1k0n** [comment]
Anything in the javascript / error console?

**Comment by TETYYS** [comment]
channel 1 invalid volume 0
xm.js:195 channel 0 invalid volume 0
xm.js:195 channel 1 invalid volume 0
xm.js:195 channel 0 invalid volume 0
xm.js:195 channel 1 invalid volume 0
xm.js:195 channel 0 invalid volume 0
xm.js:195 channel 1 invalid volume 0
xm.js:195 channel 0 invalid volume 0
xm.js:195 channel 1 invalid volume 0
xm.js:195 channel 0 invalid volume 0
2169 console messages are not shown.

**Comment by a1k0n** [comment]
whoa. can you scroll all the way up?

**Comment by TETYYS** [comment]
```
header len 336
xm.js:698 songlen 34, 4 channels, 15 patterns, 12 instruments
xm.js:699 loop @0
xm.js:700 flags=0 tempo 6 bpm 125
xm.js:706 song patterns:  [0, 0, 1, 2, 3, 3, 3, 3, 4, 4, 4, 5, 3, 3, 3, 6, 7, 8, 9, 10, 11, 11, 11, 12, 4, 4, 4, 5, 3, 3, 3, 6, 13, 14]
xm.js:715 pattern 0: 324 bytes, 64 rows
xm.js:715 pattern 1: 336 bytes, 64 rows
xm.js:715 pattern 2: 326 bytes, 64 rows
xm.js:715 pattern 3: 490 bytes, 64 rows
xm.js:715 pattern 4: 529 bytes, 64 rows
xm.js:715 pattern 5: 533 bytes, 64 rows
xm.js:715 pattern 6: 494 bytes, 64 rows
xm.js:715 pattern 7: 544 bytes, 64 rows
xm.js:715 pattern 8: 472 bytes, 64 rows
xm.js:715 pattern 9: 344 bytes, 64 rows
xm.js:715 pattern 10: 458 bytes, 64 rows
xm.js:715 pattern 11: 536 bytes, 64 rows
xm.js:715 pattern 12: 460 bytes, 64 rows
xm.js:715 pattern 13: 335 bytes, 64 rows
xm.js:715 pattern 14: 256 bytes, 64 rows
xm.js:790 hdrsiz 252; instrument 0: 'by sauli/jml' 1 samples, samphdrsiz 40
xm.js:806 sample 0: len 7850 name '' loop 2718/5130 vol 64
xm.js:808            type 1 note C-4(0) finetune 0 pan 128
xm.js:810            vol env [] 0 0 0 type 0 fadeout 0
xm.js:813            pan env [] 0 0 0 type 0
xm.js:790 hdrsiz 252; instrument 1: '' 1 samples, samphdrsiz 40
xm.js:806 sample 0: len 1202 name '' loop 0/0 vol 64
xm.js:808            type 0 note C-4(0) finetune 0 pan 128
xm.js:810            vol env [] 0 0 0 type 0 fadeout 0
xm.js:813            pan env [] 0 0 0 type 0
xm.js:790 hdrsiz 252; instrument 2: '' 1 samples, samphdrsiz 40
xm.js:806 sample 0: len 3080 name '' loop 0/0 vol 64
xm.js:808            type 0 note C-4(0) finetune 0 pan 128
xm.js:810            vol env [] 0 0 0 type 0 fadeout 0
xm.js:813            pan env [] 0 0 0 type 0
xm.js:790 hdrsiz 252; instrument 3: 'un3titled.wav' 1 samples, samphdrsiz 40
xm.js:806 sample 0: len 11394 name '' loop 0/11394 vol 64
xm.js:808            type 1 note C-4(0) finetune -128 pan 128
xm.js:810            vol env [] 0 0 0 type 0 fadeout 0
xm.js:813            pan env [] 0 0 0 type 0
xm.js:790 hdrsiz 252; instrument 4: 'disqualified entry' 1 samples, samphdrsiz 40
xm.js:806 sample 0: len 3648 name '' loop 0/0 vol 64
xm.js:808            type 0 note C-4(0) finetune 0 pan 128
xm.js:810            vol env [] 0 0 0 type 0 fadeout 0
xm.js:813            pan env [] 0 0 0 type 0
xm.js:790 hdrsiz 252; instrument 5: '' 1 samples, samphdrsiz 40
xm.js:806 sample 0: len 2876 name '' loop 0/0 vol 64
xm.js:808            type 0 note C-4(0) finetune 0 pan 128
xm.js:810            vol env [] 0 0 0 type 0 fadeout 0
xm.js:813            pan env [] 0 0 0 type 0
xm.js:790 hdrsiz 252; instrument 6: '' 1 samples, samphdrsiz 40
xm.js:806 sample 0: len 2644 name '' loop 0/0 vol 64
xm.js:808            type 0 note C-4(0) finetune 0 pan 128
xm.js:810            vol env [] 0 0 0 type 0 fadeout 0
xm.js:813            pan env [] 0 0 0 type 0
xm.js:790 hdrsiz 252; instrument 7: '' 1 samples, samphdrsiz 40
xm.js:806 sample 0: len 2860 name '' loop 0/0 vol 64
xm.js:808            type 0 note C-4(0) finetune 0 pan 128
xm.js:810            vol env [] 0 0 0 type 0 fadeout 0
xm.js:813            pan env [] 0 0 0 type 0
xm.js:790 hdrsiz 252; instrument 8: 'asm05' 1 samples, samphdrsiz 40
xm.js:806 sample 0: len 3158 name '' loop 0/0 vol 64
xm.js:808            type 0 note C-4(0) finetune 0 pan 128
xm.js:810            vol env [] 0 0 0 type 0 fadeout 0
xm.js:813            pan env [] 0 0 0 type 0
xm.js:790 hdrsiz 252; instrument 9: '' 1 samples, samphdrsiz 40
xm.js:806 sample 0: len 2448 name '' loop 0/0 vol 64
xm.js:808            type 0 note C-4(0) finetune 0 pan 128
xm.js:810            vol env [] 0 0 0 type 0 fadeout 0
xm.js:813            pan env [] 0 0 0 type 0
xm.js:790 hdrsiz 252; instrument 10: '' 1 samples, samphdrsiz 40
xm.js:806 sample 0: len 1824 name '' loop 0/0 vol 64
xm.js:808            type 0 note C-4(0) finetune 0 pan 128
xm.js:810            vol env [] 0 0 0 type 0 fadeout 0
xm.js:813            pan env [] 0 0 0 type 0
xm.js:790 hdrsiz 252; instrument 11: '' 1 samples, samphdrsiz 40
xm.js:806 sample 0: len 912 name '' loop 0/0 vol 64
xm.js:808            type 0 note C-4(0) finetune 0 pan 128
xm.js:810            vol env [] 0 0 0 type 0 fadeout 0
xm.js:813            pan env [] 0 0 0 type 0
xm.js:884 loaded "untitled"
3xm.js:195 channel 1 invalid volume 0
```

**Comment by a1k0n** [comment]
oh wait, that will show the loading of a different xm. hmm. I can't reproduce here...

**Comment by TETYYS** [comment]
> oh wait, that will show the loading of a different xm. hmm. I can't reproduce here...

I refreshed the page and just posted just the part where problematic xm loads and plays

**Comment by a1k0n** [comment]
which xm is that? none of the three you linked are called "untitled" by sauli/jml

**Comment by TETYYS** [comment]
this is https://up1.ca/#sBOBOY3VnHU9C4ySo-N_UQ

**Comment by a1k0n** [comment]
Hm, ok, yeah something is weird with that XM but it does play for me.

To be clear -- you're getting no sound and nothing on the screen, or you do have sound playing and nothing is showing up?

**Comment by TETYYS** [comment]
sound plays normally, waves are showing normally, just no notes
[screen](http://i.imgur.com/2wNRnDg.png)

**Comment by a1k0n** [comment]
Oh, crazy. You have no text whatsoever but the big font renders. Curious! You should have instrument numbers/names as well underneath. Hmmmm...

**Comment by TETYYS** [comment]
oh, i should?
this is what 'normal' is to me: [screen](http://i.imgur.com/Lyo5Tr0.png)

**Comment by a1k0n** [comment]
This is what it's supposed to do; screencap'd on a windows VM:

<img width="757" alt="screen shot 2015-11-19 at 10 24 16 am" src="https://cloud.githubusercontent.com/assets/46170/11279836/bcc27f2a-8ea7-11e5-86e3-5ca2abdebec5.png">

**Comment by TETYYS** [comment]
I get instrument names and notes on firefox.
The problem persists with all extensions disabled on chrome

**Comment by a1k0n** [comment]
It seems to be a problem with the way text is composited over other things. Could even have something to do with video drivers.

The top font is rendered with just regular blits - copying sections of ft2font.png onto the canvas. The instrument list is rendered with the 'lighten' composite operation, where the white pixels become white and the black pixels leave the background alone. And the pattern is rendered to an offscreen canvas, which is then rendered with the 'lighten' operation over the blue bar which highlights the playing row.

So the 'lighten' operation seems to be broken for you in Chrome.

**Comment by a1k0n** [comment]
btw, 32-bit or 64-bit windows/chrome? https://code.google.com/p/chromium/issues/detail?id=543342

**Comment by TETYYS** [comment]
x86 chrome x64 win

**Comment by a1k0n** [comment]
Ok, I think you're hitting https://code.google.com/p/chromium/issues/detail?id=544766

**Comment by TETYYS** [comment]
[Am I](http://i.imgur.com/Gj88Ulj.png)? I'm not sure what it does so I can't determine whether it is rendering correct or not

**Comment by a1k0n** [comment]
Hmm. Well, if you go to https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/globalCompositeOperation does your "lighten" look like this?

<img width="174" alt="screen shot 2015-11-19 at 10 42 26 am" src="https://cloud.githubusercontent.com/assets/46170/11280300/3ee90b48-8eaa-11e5-966f-d7e487a38b7e.png">

**Comment by TETYYS** [comment]
nope, it's this: ![](http://i.imgur.com/Wj8Jcvu.png)

**Comment by a1k0n** [comment]
Yeah, then it seems to be this issue: https://code.google.com/p/chromium/issues/detail?id=543583

I could try to work around this by using an alpha channel instead of blend modes, but once Chrome 46.0. 2526+ comes out it should be fixed.

**Comment by a1k0n** [comment]
@TETYYS is this fixed in Windows Chrome now?

**Comment by TETYYS** [comment]
Yes

**Comment by a1k0n** [comment]
Thanks for checking!
