### ISSUE TITLE
Global vars and namespacing

### ISSUE THREAD

**Issue by tibbon** [a1k0n/jsxm#2]
I love what you've got here. But all of the top level functions and vars are global. Encapsulating these using the module pattern or similar would be awesome for making it more structured.

**Comment by a1k0n** [comment]
Yeah, it's a complete mess. I have never developed an actual production javascript app before -- can you tell? I'll work on it.

It would also _really_ help to have unit tests for all the effects and various combinations of note on/instrument on/etc, as I keep breaking them.

**Comment by tibbon** [comment]
Tests would be awesome. I love the book JavaScript Patterns by Stoyan Stefanov for them, but there's some good online resources too. If I can find some time, I might make a PR for you.

**Comment by a1k0n** [comment]
Thanks @hillerstorm for fixing this...
