### ISSUE TITLE
Bug: 300 / M0 means "use last value" not a literal zero

### ISSUE THREAD

**Issue by Broam** [a1k0n/jsxm#24]
Channel zero of this song - the Moog sample should continue w/ the tone portamento (3xx / Mx in volume column) instead of restarting, but the effect is unimplemented.

[Broam_-_FSharp_Jump.xm.zip](https://github.com/a1k0n/jsxm/files/226946/Broam_-_FSharp_Jump.xm.zip)

Song's CC-By-SA, as noted in the sample text

**Comment by a1k0n** [comment]
Thanks for the report!

Just pushed a fix... Now you can actually hear the filter sweep in the song. Will update my site later tonight.

**Comment by a1k0n** [comment]
FWIW, 300 was implemented correctly, but Mx wasn't implemented at all.

**Comment by a1k0n** [comment]
Fixed on https://www.a1k0n.net/code/jsxm/

Thanks for the report.

**Comment by a1k0n** [comment]
However the Lxx effect isn't implemented; I believe your song uses it heavily. See #5
