### ISSUE TITLE
Desktop native app.

### ISSUE THREAD

**Issue by luckcolors** [a1k0n/jsxm#6]
It will be fairly easy to package the app using http://nwjs.io/ or  https://github.com/atom/electron for the desktop app.
I'll look into doing this :).

**Comment by PeterNerlich** [comment]
Why a desktop app of this? Wouldn't it therefor be better to use a real tracker like [Milkytracker](http://milkytracker.org/?download)?

**Comment by a1k0n** [comment]
Agreed, I don't think there's any point in a desktop version.

**Comment by luckcolors** [comment]
Yeah i should have closed this after you merged the package.json change which allowed for the app to ber run using nw.js.
Sorry about leaving the issue here. :)
